import type { Metadata } from "next";
import { Geist, Geist_Mono, Anton, Raleway } from "next/font/google";
import "./globals.css";
import Atomview from "./components/atomview";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const anton = Anton({
  variable: "--font-anton",
  weight: "400"
});

const raleway = Raleway({
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${anton.variable} ${raleway.variable} antialiased`}
      >
        <div>
          <div className="fixed h-screen w-full bg-black">
            <Atomview></Atomview>
          </div>
          <div className="fixed top-72 left-20 text-xl w-auto h-auto flex flex-col z-20 font-title font-thin">
            <Link href={"/"}>Home</Link>
            <Link href={"/aboutme"}>About me</Link>
            <Link href={"/projects"}>Projects</Link>
            <Link href={"/threeD"}>3D</Link>
            <Link href={"/contact"}>Contact</Link>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
