import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Atomview from "./components/atomview";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <div>
        <div className="fixed h-screen w-full">
        <Atomview></Atomview>
      </div>
      <div className="fixed top-80 left-32 text-xl w-auto h-auto flex flex-col z-20">
        <Link href={"/"}>Home</Link>
        <Link href={"/aboutme"}>About me</Link>
        <Link href={"/projects"}>Projects</Link>
        <Link href={"/3d"}>3D</Link>
        <Link href={"/contact"}>Contact</Link>
      </div>
      {children}
        </div>
        
        
      </body>
    </html>
  );
}
