/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
// @ts-nocheck
'use client'

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Chair(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/chair.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Chair_base"
          castShadow
          receiveShadow
          geometry={nodes.Chair_base.geometry}
          material={materials['Wood.001']}
          rotation={[Math.PI, 0, -2.974]}>
          <mesh
            name="Chair_back"
            castShadow
            receiveShadow
            geometry={nodes.Chair_back.geometry}
            material={materials['Wood.001']}
            position={[-0.139, 0.674, 0.176]}
            rotation={[1.834, -0.162, -3.098]}
          />
          <group
            name="Chair_screw1"
            position={[0.001, 0.467, -0.149]}
            rotation={[-3.083, 0.003, 3.115]}>
            <mesh
              name="Circle001"
              castShadow
              receiveShadow
              geometry={nodes.Circle001.geometry}
              material={materials.Screw}
            />
            <mesh
              name="Circle001_1"
              castShadow
              receiveShadow
              geometry={nodes.Circle001_1.geometry}
              material={materials.SrewHole}
            />
          </group>
          <group
            name="Chair_screw2"
            position={[0.001, 0.458, 0.007]}
            rotation={[-3.09, 0.004, 3.108]}>
            <mesh
              name="Circle"
              castShadow
              receiveShadow
              geometry={nodes.Circle.geometry}
              material={materials.Screw}
            />
            <mesh
              name="Circle_1"
              castShadow
              receiveShadow
              geometry={nodes.Circle_1.geometry}
              material={materials.SrewHole}
            />
          </group>
          <group
            name="Chair_screw3"
            position={[0.002, 0.599, 0.16]}
            rotation={[1.814, -0.206, 2.8]}>
            <mesh
              name="Circle002"
              castShadow
              receiveShadow
              geometry={nodes.Circle002.geometry}
              material={materials.Screw}
            />
            <mesh
              name="Circle002_1"
              castShadow
              receiveShadow
              geometry={nodes.Circle002_1.geometry}
              material={materials.SrewHole}
            />
          </group>
          <group
            name="Chair_screw4"
            position={[0.002, 0.705, 0.194]}
            rotation={[1.805, -0.193, 2.886]}>
            <mesh
              name="Circle003"
              castShadow
              receiveShadow
              geometry={nodes.Circle003.geometry}
              material={materials.Screw}
            />
            <mesh
              name="Circle003_1"
              castShadow
              receiveShadow
              geometry={nodes.Circle003_1.geometry}
              material={materials.SrewHole}
            />
          </group>
          <mesh
            name="Chair_seat"
            castShadow
            receiveShadow
            geometry={nodes.Chair_seat.geometry}
            material={materials['Wood.001']}
            position={[-0.174, 0.482, -0.045]}
            rotation={[0, 0, -0.168]}
          />
          <mesh
            name="Chair_slat"
            castShadow
            receiveShadow
            geometry={nodes.Chair_slat.geometry}
            material={materials['Wood.001']}
            position={[-0.195, 0.357, -0.179]}
            rotation={[-3.063, 0.013, -2.974]}
          />
          <mesh
            name="Chair_slat2"
            castShadow
            receiveShadow
            geometry={nodes.Chair_slat2.geometry}
            material={materials['Wood.001']}
            position={[-0.197, 0.342, 0.184]}
            rotation={[3.065, -0.013, -2.974]}
          />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/chair.glb')
