/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
//@ts-nocheck
'use client'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function guiltar(props) {
  const { nodes, materials } = useGLTF('/guitar.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.134, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_2.geometry}
          material={materials.FretBoard}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.Frets}
        position={[-0.129, 0.252, -1.964]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials.Frets}
        position={[-0.129, 0.255, -1.765]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials.Frets}
        position={[-0.129, 0.258, -1.571]}
        rotation={[0, 0.033, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials.Frets}
        position={[-0.129, 0.26, -1.391]}
        rotation={[0, 0.052, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials.Frets}
        position={[-0.129, 0.263, -1.222]}
        rotation={[0, 0.066, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials.Frets}
        position={[-0.129, 0.265, -1.056]}
        rotation={[0, 0.085, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials.Frets}
        position={[-0.129, 0.267, -0.905]}
        rotation={[0, 0.09, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={materials.Frets}
        position={[-0.129, 0.269, -0.762]}
        rotation={[0, 0.099, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={materials.Frets}
        position={[-0.129, 0.271, -0.627]}
        rotation={[0, 0.105, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={materials.Frets}
        position={[-0.129, 0.273, -0.5]}
        rotation={[0, 0.113, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={materials.Frets}
        position={[-0.129, 0.275, -0.378]}
        rotation={[0, 0.124, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={materials.Frets}
        position={[-0.129, 0.276, -0.264]}
        rotation={[0, 0.13, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012.geometry}
        material={materials.Frets}
        position={[-0.129, 0.278, -0.177]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013.geometry}
        material={materials.Frets}
        position={[-0.129, 0.279, -0.076]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder014.geometry}
        material={materials.Frets}
        position={[-0.129, 0.281, 0.017]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder015.geometry}
        material={materials.Frets}
        position={[-0.129, 0.282, 0.11]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder016.geometry}
        material={materials.Frets}
        position={[-0.129, 0.284, 0.194]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder017.geometry}
        material={materials.Frets}
        position={[-0.129, 0.285, 0.277]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder018.geometry}
        material={materials.Frets}
        position={[-0.129, 0.285, 0.351]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder019.geometry}
        material={materials.Frets}
        position={[-0.129, 0.287, 0.42]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder020.geometry}
        material={materials.Frets}
        position={[-0.129, 0.288, 0.486]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder021.geometry}
        material={materials.Frets}
        position={[-0.129, 0.288, 0.556]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder022.geometry}
        material={materials.Frets}
        position={[-0.129, 0.289, 0.612]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder023.geometry}
        material={materials.Frets}
        position={[-0.129, 0.29, 0.669]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder024.geometry}
        material={materials.Frets}
        position={[-0.128, 0.254, -2.179]}
        rotation={[0, -0.012, -Math.PI / 2]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Humbucker1.geometry}
        material={materials.Humbuckers}
        position={[0.026, 0.197, 1.41]}
        scale={[0.202, 0.241, 0.11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Humbucker2.geometry}
        material={materials.Humbuckers}
        position={[0.026, 0.191, 0.918]}
        scale={[0.202, 0.241, 0.11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SingeCoil.geometry}
        material={materials.Humbuckers}
        position={[0.023, 0.174, 1.15]}
        scale={[0.209, 0.125, 0.052]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt001.geometry}
        material={materials.Screws}
        position={[0.242, 0.208, 0.919]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt002.geometry}
        material={materials.Screws}
        position={[-0.192, 0.208, 0.919]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt003.geometry}
        material={materials.Screws}
        position={[-0.192, 0.215, 1.411]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt004.geometry}
        material={materials.Screws}
        position={[0.241, 0.218, 1.411]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bridge.geometry}
        material={materials.Hardware}
        position={[0.028, 0.279, 1.693]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bridge_tuner1.geometry}
          material={materials.Hardware}
          position={[-0.157, 0.029, 0.133]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bridge_tuner2.geometry}
          material={materials.Hardware}
          position={[-0.093, 0.029, 0.115]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bridge_tuner3.geometry}
          material={materials.Hardware}
          position={[-0.032, 0.029, 0.101]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bridge_tuner4.geometry}
          material={materials.Hardware}
          position={[0.031, 0.029, 0.085]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bridge_tuner5.geometry}
          material={materials.Hardware}
          position={[0.091, 0.029, 0.068]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bridge_tuner6.geometry}
          material={materials.Hardware}
          position={[0.155, 0.029, 0.046]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <group position={[0.236, 0.014, 0.077]} scale={[0.037, 0.019, 0.037]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder040.geometry}
            material={materials.Screws}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder040_1.geometry}
            material={materials.Hardware}
          />
        </group>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt.geometry}
        material={materials.Screws}
        position={[-0.002, 0.262, -2.244]}
        scale={0.011}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt005.geometry}
        material={materials.Screws}
        position={[0.039, 0.262, -2.211]}
        scale={0.011}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt006.geometry}
        material={materials.Screws}
        position={[0.082, 0.262, -2.244]}
        scale={0.011}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt007.geometry}
        material={materials.Screws}
        position={[-0.042, 0.262, -2.211]}
        scale={0.011}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt008.geometry}
        material={materials.Screws}
        position={[-0.083, 0.262, -2.245]}
        scale={0.011}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt009.geometry}
        material={materials.Screws}
        position={[0.125, 0.262, -2.213]}
        scale={0.011}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Hardware}
        position={[0.02, 0.278, -2.147]}
        scale={[0.124, 0.003, 0.009]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.Hardware}
        position={[0.083, 0.287, -2.243]}
        scale={0.021}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.Hardware}
        position={[-0.002, 0.287, -2.243]}
        scale={0.021}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.Hardware}
        position={[-0.082, 0.287, -2.243]}
        scale={0.021}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials.Hardware}
        position={[-0.042, 0.287, -2.201]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.021}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials.Hardware}
        position={[0.04, 0.287, -2.201]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.021}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials.Hardware}
        position={[0.123, 0.287, -2.201]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.021}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder025.geometry}
        material={materials.StringsWound}
        position={[-0.059, 0.353, -0.235]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.004, 2.053, 0.004]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder026.geometry}
        material={materials.StringsWound}
        position={[-0.122, 0.353, -0.239]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.004, 2.053, 0.004]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder027.geometry}
        material={materials.StringsWound}
        position={[0.001, 0.353, -0.235]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.003, 2.053, 0.003]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder028.geometry}
        material={materials.Strings}
        position={[0.046, 0.353, -0.235]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.002, 2.053, 0.002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder029.geometry}
        material={materials.Strings}
        position={[0.123, 0.353, -0.235]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.002, 2.053, 0.002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder030.geometry}
        material={materials.Strings}
        position={[0.187, 0.353, -0.291]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.002, 2.053, 0.002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder031.geometry}
        material={materials.Screws}
        position={[-0.435, 0.207, 0.522]}
        scale={[0.019, 0.063, 0.019]}
      />
      <group position={[0.469, 0.286, 1.754]} scale={[0.054, 0.055, 0.054]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder037.geometry}
          material={materials.Screws}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder037_1.geometry}
          material={materials.Rubber}
        />
      </group>
      <group position={[0.673, 0.258, 1.604]} scale={[0.054, 0.055, 0.054]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_25.geometry}
          material={materials.Screws}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_26.geometry}
          material={materials.Rubber}
        />
      </group>
      <group
        position={[0.583, 0.182, 1.326]}
        rotation={[-1.143, 0.211, 0.332]}
        scale={[0.004, 0.093, 0.015]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_27.geometry}
          material={materials.Screws}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_28.geometry}
          material={materials.Rubber}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/guitar.glb')
