/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube006_1: THREE.Mesh
    Cube006_2: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder004: THREE.Mesh
    Cylinder005: THREE.Mesh
    Cylinder006: THREE.Mesh
    Cylinder007: THREE.Mesh
    Cylinder008: THREE.Mesh
    Cylinder009: THREE.Mesh
    Cylinder010: THREE.Mesh
    Cylinder011: THREE.Mesh
    Cylinder012: THREE.Mesh
    Cylinder013: THREE.Mesh
    Cylinder014: THREE.Mesh
    Cylinder015: THREE.Mesh
    Cylinder016: THREE.Mesh
    Cylinder017: THREE.Mesh
    Cylinder018: THREE.Mesh
    Cylinder019: THREE.Mesh
    Cylinder020: THREE.Mesh
    Cylinder021: THREE.Mesh
    Cylinder022: THREE.Mesh
    Cylinder023: THREE.Mesh
    Cylinder024: THREE.Mesh
    Humbucker1: THREE.Mesh
    Humbucker2: THREE.Mesh
    SingeCoil: THREE.Mesh
    SingleCoil_Magnet1: THREE.Mesh
    SingleCoil_Magnet2: THREE.Mesh
    SingleCoil_Magnet3: THREE.Mesh
    Bolt001: THREE.Mesh
    Bolt002: THREE.Mesh
    Bolt003: THREE.Mesh
    Bolt004: THREE.Mesh
    Bridge: THREE.Mesh
    Bridge_tuner1: THREE.Mesh
    Tuner_saddle: THREE.Mesh
    Bridge_tuner2: THREE.Mesh
    Tuner_saddle001: THREE.Mesh
    Bridge_tuner3: THREE.Mesh
    Tuner_saddle002: THREE.Mesh
    Bridge_tuner4: THREE.Mesh
    Tuner_saddle003: THREE.Mesh
    Bridge_tuner5: THREE.Mesh
    Tuner_saddle004: THREE.Mesh
    Bridge_tuner6: THREE.Mesh
    Tuner_saddle005: THREE.Mesh
    Cylinder040: THREE.Mesh
    Cylinder040_1: THREE.Mesh
    Bolt: THREE.Mesh
    Bolt005: THREE.Mesh
    Bolt006: THREE.Mesh
    Bolt007: THREE.Mesh
    Bolt008: THREE.Mesh
    Bolt009: THREE.Mesh
    Cube: THREE.Mesh
    Cube002: THREE.Mesh
    Cube003: THREE.Mesh
    Cube004: THREE.Mesh
    Cube005: THREE.Mesh
    Cube006: THREE.Mesh
    Cube007: THREE.Mesh
    Cylinder025: THREE.Mesh
    Cylinder026: THREE.Mesh
    Cylinder027: THREE.Mesh
    Cylinder028: THREE.Mesh
    Cylinder029: THREE.Mesh
    Cylinder030: THREE.Mesh
    Cylinder031: THREE.Mesh
    Cylinder037: THREE.Mesh
    Cylinder037_1: THREE.Mesh
    Mesh_25: THREE.Mesh
    Mesh_26: THREE.Mesh
    Mesh_27: THREE.Mesh
    Mesh_28: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshPhysicalMaterial
    FretBoard: THREE.MeshStandardMaterial
    Screws: THREE.MeshStandardMaterial
    Humbuckers: THREE.MeshStandardMaterial
    ['Strings.001']: THREE.MeshStandardMaterial
    ['Strings.003']: THREE.MeshStandardMaterial
    ['Strings.002']: THREE.MeshStandardMaterial
    Hardware: THREE.MeshPhysicalMaterial
    Strings: THREE.MeshStandardMaterial
    Rubber: THREE.MeshStandardMaterial
  }
}

/* @ts-ignore */
export default function Guitar(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/guitar.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.1336, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_2.geometry}
          material={materials.FretBoard}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2523, -1.9644]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2551, -1.765]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.258, -1.5707]}
        rotation={[0, 0.0329, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2601, -1.3907]}
        rotation={[0, 0.0518, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2633, -1.2218]}
        rotation={[0, 0.0656, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2653, -1.0563]}
        rotation={[0, 0.0848, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2675, -0.9051]}
        rotation={[0, 0.0898, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2693, -0.7623]}
        rotation={[0, 0.0988, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2712, -0.6274]}
        rotation={[0, 0.1051, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.273, -0.4998]}
        rotation={[0, 0.1126, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2749, -0.3775]}
        rotation={[0, 0.1236, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2761, -0.2637]}
        rotation={[0, 0.1302, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2779, -0.177]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2794, -0.0762]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder014.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2807, 0.0174]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder015.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.282, 0.1097]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder016.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2837, 0.1935]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder017.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2846, 0.2774]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder018.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2855, 0.3515]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder019.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2868, 0.4197]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder020.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2877, 0.486]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder021.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2885, 0.5556]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder022.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2894, 0.6121]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder023.geometry}
        material={materials.Screws}
        position={[-0.1293, 0.2898, 0.6687]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder024.geometry}
        material={materials.Screws}
        position={[-0.1282, 0.254, -2.1789]}
        rotation={[0, -0.0121, -Math.PI / 2]}
        scale={0.0469}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Humbucker1.geometry}
        material={materials.Humbuckers}
        position={[0.0256, 0.1967, 1.4105]}
        scale={[0.2017, 0.2411, 0.1096]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Humbucker2.geometry}
        material={materials.Humbuckers}
        position={[0.0256, 0.191, 0.9178]}
        scale={[0.2017, 0.2411, 0.1096]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SingeCoil.geometry}
        material={materials.Humbuckers}
        position={[0.0234, 0.1736, 1.1501]}
        scale={[0.209, 0.1245, 0.0517]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SingleCoil_Magnet1.geometry}
          material={materials['Strings.001']}
          position={[0.151, 0.9488, 0.0019]}
          scale={[0.0575, 0.0965, 0.2326]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SingleCoil_Magnet2.geometry}
          material={materials['Strings.003']}
          position={[0.4507, 0.9488, 0.0019]}
          scale={[0.0575, 0.0965, 0.2326]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SingleCoil_Magnet3.geometry}
          material={materials['Strings.002']}
          position={[0.7498, 0.9488, 0.0019]}
          scale={[0.0575, 0.0965, 0.2326]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt001.geometry}
        material={materials.Screws}
        position={[0.2416, 0.2085, 0.9187]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt002.geometry}
        material={materials.Screws}
        position={[-0.1915, 0.2085, 0.9187]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt003.geometry}
        material={materials.Screws}
        position={[-0.1915, 0.2153, 1.4114]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt004.geometry}
        material={materials.Screws}
        position={[0.2415, 0.2185, 1.4114]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bridge.geometry}
        material={materials.Hardware}
        position={[0.0285, 0.2793, 1.6931]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bridge_tuner1.geometry}
          material={materials.Hardware}
          position={[-0.1573, 0.0291, 0.1327]}
          rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tuner_saddle.geometry}
            material={materials.Screws}
            position={[0.0005, 0.1073, 0.0243]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.0084}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bridge_tuner2.geometry}
          material={materials.Hardware}
          position={[-0.0931, 0.0291, 0.1153]}
          rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tuner_saddle001.geometry}
            material={materials.Screws}
            position={[0.0005, 0.1073, 0.0243]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.0084}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bridge_tuner3.geometry}
          material={materials.Hardware}
          position={[-0.0324, 0.0291, 0.101]}
          rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tuner_saddle002.geometry}
            material={materials.Screws}
            position={[0.0005, 0.1073, 0.0243]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.0084}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bridge_tuner4.geometry}
          material={materials.Hardware}
          position={[0.0306, 0.0291, 0.085]}
          rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tuner_saddle003.geometry}
            material={materials.Screws}
            position={[0.0005, 0.1073, 0.0243]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.0084}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bridge_tuner5.geometry}
          material={materials.Hardware}
          position={[0.0914, 0.0291, 0.0684]}
          rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tuner_saddle004.geometry}
            material={materials.Screws}
            position={[0.0005, 0.1073, 0.0243]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.0084}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bridge_tuner6.geometry}
          material={materials.Hardware}
          position={[0.1546, 0.0291, 0.0463]}
          rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tuner_saddle005.geometry}
            material={materials.Screws}
            position={[0.0005, 0.1073, 0.0243]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.0084}
          />
        </mesh>
        <group position={[0.2364, 0.0145, 0.077]} scale={[0.0367, 0.0189, 0.0367]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder040.geometry}
            material={materials.Screws}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder040_1.geometry}
            material={materials.Hardware}
          />
        </group>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt.geometry}
        material={materials.Screws}
        position={[-0.0017, 0.2616, -2.2437]}
        scale={0.0113}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt005.geometry}
        material={materials.Screws}
        position={[0.0392, 0.2616, -2.2113]}
        scale={0.0113}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt006.geometry}
        material={materials.Screws}
        position={[0.0824, 0.2616, -2.2439]}
        scale={0.0113}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt007.geometry}
        material={materials.Screws}
        position={[-0.0417, 0.2616, -2.2115]}
        scale={0.0113}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt008.geometry}
        material={materials.Screws}
        position={[-0.0832, 0.2616, -2.245]}
        scale={0.0113}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt009.geometry}
        material={materials.Screws}
        position={[0.1245, 0.2616, -2.2127]}
        scale={0.0113}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Hardware}
        position={[0.0203, 0.2779, -2.1475]}
        scale={[0.1236, 0.0034, 0.0092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.Hardware}
        position={[0.0825, 0.2868, -2.243]}
        scale={0.0213}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.Hardware}
        position={[-0.0019, 0.2868, -2.243]}
        scale={0.0213}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.Hardware}
        position={[-0.082, 0.2868, -2.243]}
        scale={0.0213}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials.Hardware}
        position={[-0.0417, 0.2868, -2.2005]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.0213}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials.Hardware}
        position={[0.0403, 0.2868, -2.2005]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.0213}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials.Hardware}
        position={[0.1227, 0.2868, -2.2005]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.0213}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder025.geometry}
        material={materials.Strings}
        position={[-0.0589, 0.3528, -0.2349]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.0036, 2.0532, 0.0036]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder026.geometry}
        material={materials.Strings}
        position={[-0.1221, 0.3528, -0.2392]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.0038, 2.0532, 0.0038]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder027.geometry}
        material={materials.Strings}
        position={[0.0006, 0.3528, -0.2349]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.0029, 2.0532, 0.0029]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder028.geometry}
        material={materials.Strings}
        position={[0.0461, 0.3528, -0.2349]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.0021, 2.0532, 0.0021]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder029.geometry}
        material={materials.Strings}
        position={[0.1227, 0.3528, -0.2349]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.0021, 2.0532, 0.0021]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder030.geometry}
        material={materials.Strings}
        position={[0.1872, 0.3528, -0.2906]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.0018, 2.0532, 0.0018]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder031.geometry}
        material={materials.Screws}
        position={[-0.4353, 0.2072, 0.5215]}
        scale={[0.0193, 0.0628, 0.0193]}
      />
      <group position={[0.4685, 0.2864, 1.7538]} scale={[0.0537, 0.0553, 0.0537]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder037.geometry}
          material={materials.Screws}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder037_1.geometry}
          material={materials.Rubber}
        />
      </group>
      <group position={[0.6731, 0.2581, 1.6042]} scale={[0.0537, 0.0553, 0.0537]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_25.geometry}
          material={materials.Screws}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_26.geometry}
          material={materials.Rubber}
        />
      </group>
      <group
        position={[0.5833, 0.1816, 1.326]}
        rotation={[-1.1425, 0.2113, 0.3319]}
        scale={[0.0044, 0.093, 0.0153]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_27.geometry}
          material={materials.Screws}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_28.geometry}
          material={materials.Rubber}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/guitar.glb')
